# PostgreSQL v0.9.x
#   gem install pg
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: dankira2_development
  pool: 5
  username: myUbuntu
  password: password
  
 test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: dankira2_test
  pool: 5
  username: myUbuntu
  password: password

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: dankira2_production
  pool: 5
  username: myUbuntu
  password: password
